import { NextResponse } from "next/server"

// Mock data matching the structure from your JSON
const mockData = {
  cursor: {
    currentPage: "",
    nextPage: "",
    previousPages: [],
  },
  list: [
    {
      activeTicketsCount: 0,
      avgHandlingTime: 393,
      avgWaitTime: 0,
      casesBacklog: 0,
      channel: "chat",
      country: "ES",
      department: "VS",
      expertise: "tier1",
      id: "a3aa1bd6-f742-4589-933a-535837bdbbaa",
      language: "spa",
      longestWaitTime: 0,
      onlineAgentCount: 3,
      queueName: "VS-chat-spa-ES-tier1",
      totalAgentCount: 390,
    },
    {
      activeTicketsCount: 148,
      avgHandlingTime: 807,
      avgWaitTime: 13316,
      casesBacklog: 283,
      channel: "case-inbox",
      country: "ES",
      department: "VS",
      expertise: "tier2",
      id: "c980f7d3-27a6-464f-8405-d73e768b3e01",
      language: "spa",
      longestWaitTime: 19747,
      onlineAgentCount: 0,
      queueName: "VS-case-inbox-spa-ES-tier2",
      totalAgentCount: 270,
    },
    {
      activeTicketsCount: 0,
      avgHandlingTime: 0,
      avgWaitTime: 0,
      casesBacklog: 0,
      channel: "case-inbox",
      country: "ES",
      department: "VS",
      expertise: "tier1",
      id: "7b36c3ee-f076-4020-9d36-08a14a1756e0",
      language: "spa",
      longestWaitTime: 0,
      onlineAgentCount: 0,
      queueName: "VS-case-inbox-spa-ES-tier1",
      totalAgentCount: 124,
    },
    {
      activeTicketsCount: 787,
      avgHandlingTime: -356,
      avgWaitTime: 322555,
      casesBacklog: 10000,
      channel: "case-inbox",
      country: "ES",
      department: "VS",
      expertise: "disputes",
      id: "1e17de46-d9a8-4815-996b-4b3baff51ad9",
      language: "spa",
      longestWaitTime: 450081,
      onlineAgentCount: 0,
      queueName: "VS-case-inbox-spa-ES-disputes",
      totalAgentCount: 140,
    },
    {
      activeTicketsCount: 0,
      avgHandlingTime: 0,
      avgWaitTime: 0,
      casesBacklog: 0,
      channel: "chat",
      country: "ES",
      department: "RS",
      expertise: "tier2",
      id: "b8e1e1d2-4298-406b-b38d-3d4500ecd36d",
      language: "spa",
      longestWaitTime: 0,
      onlineAgentCount: 0,
      queueName: "RS-chat-spa-ES-tier2",
      totalAgentCount: 98,
    },
    {
      activeTicketsCount: 0,
      avgHandlingTime: 216,
      avgWaitTime: 0,
      casesBacklog: 0,
      channel: "chat",
      country: "ES",
      department: "RS",
      expertise: "tier1",
      id: "5295c718-0801-4196-afb3-4329ed8caab4",
      language: "spa",
      longestWaitTime: 0,
      onlineAgentCount: 6,
      queueName: "RS-chat-spa-ES-tier1",
      totalAgentCount: 454,
    },
    {
      activeTicketsCount: 0,
      avgHandlingTime: 642,
      avgWaitTime: 20897,
      casesBacklog: 562,
      channel: "case-inbox",
      country: "ES",
      department: "RS",
      expertise: "tier2",
      id: "145a72a8-d4f7-4e21-a9d3-3094e0f99ad6",
      language: "spa",
      longestWaitTime: 31150,
      onlineAgentCount: 0,
      queueName: "RS-case-inbox-spa-ES-tier2",
      totalAgentCount: 136,
    },
    {
      activeTicketsCount: 0,
      avgHandlingTime: 0,
      avgWaitTime: 0,
      casesBacklog: 0,
      channel: "chat",
      country: "ES",
      department: "CS",
      expertise: "tier1",
      id: "c59d5558-d515-46b6-8cfd-08750934a0d0",
      language: "spa",
      longestWaitTime: 0,
      onlineAgentCount: 0,
      queueName: "CS-chat-spa-ES-tier1",
      totalAgentCount: 617,
    },
    {
      activeTicketsCount: 2,
      avgHandlingTime: 600,
      avgWaitTime: 7,
      casesBacklog: 1,
      channel: "chat",
      country: "ES",
      department: "CS",
      expertise: "nonlive-order",
      id: "4d9d83b3-8e3f-4937-8870-caf43e8410fc",
      language: "spa",
      longestWaitTime: 7,
      onlineAgentCount: 2,
      queueName: "CS-chat-spa-ES-nonlive-order",
      totalAgentCount: 1221,
    },
    {
      activeTicketsCount: 5,
      avgHandlingTime: 511,
      avgWaitTime: 0,
      casesBacklog: 0,
      channel: "chat",
      country: "ES",
      department: "CS",
      expertise: "live-order",
      id: "08dad2b8-2971-4c17-9d64-0dab991a8ce7",
      language: "spa",
      longestWaitTime: 0,
      onlineAgentCount: 2,
      queueName: "CS-chat-spa-ES-live-order",
      totalAgentCount: 733,
    },
    {
      activeTicketsCount: 78,
      avgHandlingTime: 736,
      avgWaitTime: 29904,
      casesBacklog: 3973,
      channel: "case-inbox",
      country: "ES",
      department: "CS",
      expertise: "tier2",
      id: "9c5c3b38-71f9-468a-ba71-b440c8e31845",
      language: "spa",
      longestWaitTime: 51058,
      onlineAgentCount: 2,
      queueName: "CS-case-inbox-spa-ES-tier2",
      totalAgentCount: 397,
    },
  ],
  pageSize: 11,
}

export async function GET() {
  // Simulate network delay
  await new Promise((resolve) => setTimeout(resolve, 500))
  
  return NextResponse.json(mockData)
}
